from __future__ import annotations

import re
from collections.abc import Mapping
from dataclasses import dataclass
from types import MappingProxyType
from typing import Callable, Iterable, Literal

from mmalignments.utils import as_tuple

_GENE_ANNOTATIONS = {
    "gene_stable_id": "META",
    "name": "META",
    "chr": "META",
    "start": "META",
    "stop": "META",
    "strand": "META",
    "tss": "META",
    "tes": "META",
    "biotype": "META",
    "transcript_stable_ids": "META",
}


@dataclass(frozen=True)
class View:
    """
    metric : str | tuple[str, ...] | None, optional
        The metric prefix to filter by. If None, do not filter by metric.
    sample_id : str | tuple[str, ...] | None, optional
        The sample ID or sequence of sample IDs to filter by. If None, do
        not filter by sample ID.
    """

    # role: Role | None = None
    metric: str | tuple[str, ...] | None = None
    sample_id: str | tuple[str, ...] | None = None
    pipeline: str | None = None  #  e.g. "STAR_UMI-tools_dedup-directional"


_VIEWS = {  # often used, for convenience
    "gu": View(metric=("Count", "GU")),
    "gud": View(metric=("Count", "GU", "Dedup")),
    "esc": View(metric=("Count", "ES")),
    "escd": View(metric=("Count", "ES", "Dedup")),
    "vst": View(metric=("VST",)),
    "log2fc": View(metric=("Log2FC",)),
    "zscore": View(metric=("Z",)),
}


KNOWN_METRICS: dict[str, str] = {
    "gu": "Gene unstranded count",
    "gud": "Gene unstranded count deduplicated",
    "esc": "Exon stranded count",
    "escd": "Exon stranded count, deduplicated",
    "vst": "Variance-stabilised transformation (DESeq2)",
    "zscore": "Z-standardized score",
}


def describe_metric(segment: str) -> str:
    return KNOWN_METRICS.get(segment, f"(unknown metric segment: {segment!r})")


_CATEGORY_METRIC = {
    ("exon, protein coding, stranded", True): _VIEWS["escd"].metric,  # dedup
    ("exon, protein coding, stranded", False): _VIEWS["esc"].metric,  # no dedup
    ("gene unstranded", True): _VIEWS["gud"].metric,  # dedup
    ("gene unstranded", False): _VIEWS["gu"].metric,  # no dedup
}

################################################################################
# Legacy column name parsing
################################################################################


def _legacy_to_tag(colname: str, sample_names: list[str]) -> ColumnTag | None:
    if colname in _GENE_ANNOTATIONS:
        return ColumnTag(
            metric=(colname,),
            sample_id=None,  # role=_GENE_ROLES[colname]
            pipeline=_GENE_ANNOTATIONS[colname],  # e.g. "META"
        )  # leave as is
    else:
        m = re.match(r"^(?P<category>.+?)\s+tag count\s+(?P<rest>.+)$", colname)
        if not m:
            return None
        category = m.group("category").strip().lower()
        rest = m.group("rest").strip()

        # längste bekannte sample_id matchen, die 'rest' als Prefix hat
        sample_id = max(
            (s for s in sample_names if rest == s or rest.startswith(s + "_")),
            key=len,
            default=None,
        )
        if sample_id is None:
            raise ValueError(
                f"Could not match any known sample_id in column: {colname!r}"
            )

        pipeline = rest[len(sample_id) :].lstrip(
            "_"
        )  # e.g. "STAR_UMI-tools_dedup-directional"

        is_dedup = "dedup" in pipeline.lower()
        role_metric = _CATEGORY_METRIC.get((category, is_dedup))
        if role_metric is None:
            raise ValueError(
                f"Unknown category/dedup combination: {(category, is_dedup)}"
            )
        return ColumnTag(
            metric=tuple(role_metric),
            sample_id=sample_id,
            pipeline=None,  # pipeline
        )


################################################################################
# use Column Tags for selecting
################################################################################

# A regular expression pattern to match canonical column names in the format:
# "<metric> (<sample>)[pipeline]"
_COL_PATTERN = re.compile(
    r"""
    ^
    (?P<metric>[^\[(]+?)          # metric
    (?:\s*\((?P<sample>[^()]+)\))? # optional (sample)
    (?:\s*\[(?P<pipeline>[^\[\]]+)\])? # optional [pipeline]
    $
    """,
    re.VERBOSE,
)


@dataclass(frozen=True)
class ColumnTag:
    """
    A tag that describes a column in a DataFrame, including its metric,
    sample ID, and pipeline. Used for easy selection and filtering of columns
    based on their characteristics.
    """

    metric: tuple[str, ...] | str
    sample_id: str | None = None
    pipeline: str | None = None  # "STAR_UMI-tools_dedup-directional", optional

    @classmethod
    def decode(cls, colname: str) -> ColumnTag:
        """
        Decode a canonical column name into a ColumnTag.

        The column name must follow the format generated by ColumnTag.encode().

        Parameters
        ----------
        colname : str
            The canonical column name to decode.
        # role : Role
        #     The role associated with the column.

        Returns
        -------
        ColumnTag | None
            The decoded ColumnTag if the column name matches the expected
            format, otherwise None.
        """
        m = _COL_PATTERN.match(colname.strip())
        if not m:
            return ColumnTag(
                metric=(colname.strip(),),
                sample_id=None,
                pipeline=None,
            )

        sample = m.group("sample")
        pipeline = m.group("pipeline")

        return cls(
            metric=tuple(
                part.strip() for part in m.group("metric").strip().split(".")
            ),  # noqa: E501
            sample_id=sample.strip() if sample else None,
            pipeline=pipeline.strip() if pipeline else None,
        )

    def encode(self) -> str:
        """
        Generate a canonical column name from the tag's attributes.

        Returns
        -------
        str
            The canonical column name generated from the tag's attributes.
        """
        column_name = f"{'.'.join(self.metric)}"
        if self.sample_id:
            column_name = f"{column_name} ({self.sample_id})"
        if self.pipeline:
            column_name = f"{column_name} [{self.pipeline}]"
        return column_name

    @classmethod
    def generate_new_tag(
        cls,
        old_tag: ColumnTag,
        view: View,
        append: bool = True,
    ) -> ColumnTag:
        if append:
            new_metric = (
                as_tuple(old_tag.metric) + as_tuple(view.metric)
                if view.metric is not None
                else old_tag.metric
            )
        else:
            new_metric = as_tuple(view.metric)
        sample_id = (
            view.sample_id
            if view.sample_id is not None and isinstance(view.sample_id, str)
            else old_tag.sample_id
        )
        pipeline = old_tag.pipeline if view.pipeline is None else view.pipeline
        new_tag = ColumnTag(
            metric=new_metric,
            sample_id=sample_id,
            pipeline=pipeline,
        )
        return new_tag

    @classmethod
    def rename_columns(
        cls, columns: list[str], view: View, append: bool = True
    ) -> dict[str, str]:
        rename = {}
        for col in columns:
            old = cls.decode(col)
            new_tag = cls.generate_new_tag(old, view=view, append=append)
            rename[col] = new_tag.encode()
        return rename

    def matches_view(self, view: View) -> bool:
        """
        Check if a ColumnTag matches the criteria specified in a View.

        Parameters
        ----------
        tag : ColumnTag
            The ColumnTag to check against the View.
        view : View
            The View containing filtering criteria.

        Returns
        -------
        bool
            True if the ColumnTag matches the View's criteria, False otherwise.
        """
        tag = self
        metric_match = False
        pipeline_match = False
        sample_match = False
        if view.metric is None:
            metric_match = True
        elif isinstance(view.metric, str) and isinstance(tag.metric, tuple):
            metric_match = tag.metric == (view.metric,)
        else:
            metric_match = tag.metric == view.metric
        if view.pipeline is None:
            pipeline_match = True
        else:
            pipeline_match = tag.pipeline == view.pipeline

        if view.sample_id is None:
            sample_match = True
        elif isinstance(view.sample_id, str):
            sample_match = tag.sample_id == view.sample_id
        else:
            sample_match = tag.sample_id in view.sample_id
        print(tag.metric, view.metric)
        print(metric_match, pipeline_match, sample_match)
        return metric_match and pipeline_match and sample_match

    @classmethod
    def select_from_view(
        cls, columns: list[str], view: View | None = None
    ) -> list[str]:
        """
        Select columns from a list based on a View.

        This method filters the given list of column names, returning only those
        that match the criteria specified in the provided View. To be used to select
        DataFrame columns.

        Parameters
        ----------
        columns : list[str]
            The list of column names to filter.
        view : View | None, optional
            The View containing filtering criteria. If None, all columns are returned.

        Returns
        -------
        list[str]
            A list of column names that match the specified filtering criteria.
        """
        selected = []
        if view is None:
            return columns
        for col in columns:
            tag = cls.decode(col)
            if tag.matches_view(view):
                selected.append(col)
        return selected


class ColumnSchema(Mapping[str, ColumnTag]):
    """
    A schema that describes the columns in a DataFrame using ColumnTags.
    Provides methods for selecting and deselecting columns based on their tags.
    """

    __slots__ = ("_tags", "_index_column")

    def __init__(
        self,
        tags: Mapping[str, ColumnTag],
        index_column: str | None = None,
    ):
        """
        Initialize the ColumnSchema with a mapping of columnnames to ColumnTags.

        Parameters
        ----------
        tags : Mapping[str, ColumnTag]
            A mapping from column names to their corresponding ColumnTags.
        """
        object.__setattr__(self, "_tags", MappingProxyType(dict(tags)))
        object.__setattr__(self, "_index_column", index_column)

    def __getitem__(self, key: str) -> ColumnTag:
        return self._tags[key]

    def __iter__(self):
        return iter(self._tags)

    def __len__(self) -> int:
        return len(self._tags)

    ############################################################################
    # Selection and filtering methods
    ############################################################################

    def with_columns(self, tags: Mapping[str, ColumnTag]) -> ColumnSchema:
        overlap = set(tags) & set(self._tags)
        if overlap:
            raise KeyError(f"Columns already in schema: {overlap}")
        return ColumnSchema({**self._tags, **tags})

    def _matches(
        self,
        tag: ColumnTag,
        view: View,
    ) -> bool:
        """
        Check if a column tag matches the given filtering criteria.

        This method is used internally by the select and deselect methods to
        determine if a column should be included based on its role, metric
        prefix and sample ID.

        Parameters
        ----------
        tag : ColumnTag
            The ColumnTag to check against the filtering criteria.
        view : View
            The view containing filtering criteria.

        Returns
        -------
        bool
            True if the tag matches all specified criteria, False otherwise.
        """
        # if role is not None and tag.role != role:
        #     return False
        # if (
        #     metric_prefix is not None
        #     and tag.metric[: len(metric_prefix)] != metric_prefix
        # ):
        #     return False
        # if samples is not None and tag.sample_id not in samples:
        #     return False
        # return True
        return tag.matches_view(view)

    def select(
        self,
        view: View | None = None,
    ) -> list[str]:
        """
        Select columns based on their tags.

        This method allows filtering columns by their role, metric prefix, and
        sample ID.

        Parameters
        ----------

        Returns
        -------
        list[str]
            A list of column names that match the specified filtering criteria.
        """
        if view is None:
            return list(self._tags.keys())
        return [
            col
            for col, tag in self._tags.items()
            if self._matches(
                tag,
                view=view,
            )
        ]

    def deselect(
        self,
        view: View | None = None,
    ) -> list[str]:
        """
        Deselect columns based on their tags.

        This method allows filtering columns by their role, metric prefix, and
        sample ID, and returns the columns that do NOT match the specified
        criteria.


        Parameters
        ----------
        view : View | None, optional
            The view containing filtering criteria. If None, do not filter by
            role, metric, or sample ID.

        Returns
        -------
        list[str]
            A list of column names that do NOT match the specified filtering
            criteria.
        """
        if view is None:
            return []
        return [
            col
            for col, tag in self._tags.items()
            if not self._matches(tag, view=view)  # noqa: E501
        ]

    def derive(
        self,
        columns: Iterable[str],
        *,
        view_new: View | None = None,
        append: bool = False,
    ) -> tuple[ColumnSchema, dict[str, str]]:
        """
        Derive new columns from existing ones by modifying their tags.
        Also returns a mapping from old column names to new column names, to
        rename newly created columns.

        Parameters
        ----------
        columns : Iterable[str]
            Existing column names that must be tagged in the schema.
        add_metric : str | tuple[str, ...]
            Appended to tag.metric, e.g., "vst" -> metric + ("vst",)
        # role : Role
        #     New role for the derived columns.
        pipeline : str | None
            If not specified (sentinel), the pipeline field from the original
            tag is used. Explicit None deletes it, a string sets it anew.
        append : bool, optional
            If True, the new metric is appended to the existing metric. If
            False the new metric replaces the existing metric. Default is False.

        Returns
        -------
        tuple[ColumnSchema, dict[str, str]]
            The derived column schema and a mapping from old column names to new
            column names.
        """

        def as_tuple(x: str | tuple[str, ...]) -> tuple[str, ...]:
            return (x,) if isinstance(x, str) else x

        new_tags: dict[str, ColumnTag] = {}
        rename: dict[str, str] = {}
        for col in columns:
            old_tag = self.get(col)
            if old_tag is None:
                raise KeyError(
                    f"Column {col!r} not found in schema; cannot derive from it."  # noqa: E501
                )

            new_metric = (
                view_new.metric
                if view_new and view_new.metric is not None
                else old_tag.metric
            )
            if append and old_tag.metric is not None:
                if isinstance(new_metric, (str, tuple)):
                    new_metric = as_tuple(old_tag.metric) + as_tuple(new_metric)
                else:
                    raise TypeError(
                        f"Expected new_metric to be str or tuple, got {type(new_metric)}"  # noqa: E501
                    )
            new_pipeline = (
                view_new.pipeline
                if view_new and view_new.pipeline is not None
                else old_tag.pipeline
            )
            sample_ids = (
                old_tag.sample_id if old_tag.sample_id is not None else (None,)
            )  # noqa: E501
            if view_new and view_new.sample_id is not None:
                sample_ids = as_tuple(view_new.sample_id)

            for sample_id in sample_ids:
                new_tag = ColumnTag(
                    metric=new_metric,
                    sample_id=sample_id,
                    pipeline=new_pipeline,
                )
                new_name = new_tag.encode()
                if new_name in new_tags:
                    raise ValueError(
                        f"Duplicate derived column name: {new_name!r} (from {col!r})"  # noqa: E501
                    )

                new_tags[new_name] = new_tag
                rename[col] = new_name

        return ColumnSchema(new_tags), rename

    @staticmethod
    def derive_from_columns(
        columns: Iterable[str],
        index_column: str | None = None,
    ) -> ColumnSchema:
        """
        Derive new columns from existing ones by modifying their tags.
        Also returns a mapping from old column names to new column names, to
        rename newly created columns.

        Parameters
        ----------
        columns : Iterable[str]
            Existing column names that must be tagged in the schema.
        add_metric : str | tuple[str, ...]
            Appended to tag.metric, e.g., "vst" -> metric + ("vst",)
        # role : Role
        #     New role for the derived columns.
        pipeline : str | None
            If not specified (sentinel), the pipeline field from the original
            tag is used. Explicit None deletes it, a string sets it anew.
        append : bool, optional
            If True, the new metric is appended to the existing metric. If
            False, the new metric replaces the existing metric.
            Default is False.

        Returns
        -------
        tuple[ColumnSchema, dict[str, str]]
            The derived column schema and a mapping from old column names to new
            column names.
        """

        new_tags: dict[str, ColumnTag] = {}

        for col in columns:
            new_tag = ColumnTag.decode(col)
            new_name = new_tag.encode() if new_tag else col
            if new_name in new_tags:
                raise ValueError(
                    f"Duplicate derived column name: {new_name!r} (from {col!r})"  # noqa: E501
                )
            new_tags[new_name] = new_tag

        return ColumnSchema(new_tags, index_column=index_column)

    @staticmethod
    def derive_from_view(view_out: View) -> ColumnSchema:
        """
        Derive a new ColumnSchema based on a future output view.

        Parameters
        ----------
        view_out : View
            The output view containing the new metric and pipeline information.
        append : bool, optional
            If True, the new metric is appended to the existing metric. If
            False, it replaces the existing metric. By default False.

        Returns
        -------
        ColumnSchema
            A new ColumnSchema instance with the updated metric and pipeline.
        """
        new_tags: dict[str, ColumnTag] = {}
        if view_out.sample_id is None:
            return ColumnSchema({})
        metrics_to_produce = [""]
        if isinstance(view_out.metric, list):
            metrics_to_produce = view_out.metric
        elif isinstance(view_out.metric, (str, tuple)):
            metrics_to_produce = [view_out.metric]

        for sample in view_out.sample_id:
            for metric in metrics_to_produce:
                new_tag = ColumnTag(
                    metric=metric if isinstance(metric, tuple) else (metric,),
                    sample_id=sample,
                    pipeline=view_out.pipeline,
                )
                new_name = new_tag.encode()
                if new_name in new_tags:
                    raise ValueError(
                        f"Duplicate derived column name: {new_name!r} (from sample {sample!r})"  # noqa: E501
                    )
                new_tags[new_name] = new_tag
        return ColumnSchema(new_tags)

    def drop(self, columns: Iterable[str]) -> ColumnSchema:
        """
        Drop columns from the schema.

        Returns a new ColumnSchema instance without the specified columns.

        Parameters
        ----------
        columns : Iterable[str]
            Column names to drop from the schema.

        Returns
        -------
        ColumnSchema
            A new ColumnSchema instance without the specified columns.

        Raises
        ------
        KeyError
            If any of the specified columns are not present in the schema.
        """
        to_drop = set(columns)
        missing = to_drop - set(self._tags)
        if missing:
            raise KeyError(f"Cannot drop unknown columns: {missing}")
        return ColumnSchema(
            {k: v for k, v in self._tags.items() if k not in to_drop}
        )  # noqa: E501

    @classmethod
    def build(cls, columns: Iterable[str]) -> "ColumnSchema":
        """
        Build a ColumnSchema for columns that all share the same role.

        Parameters
        ----------
        columns : Iterable[str]
            column names from DataFrame or other source.
        role : Role
            The role to assign to all columns in the schema.

        Returns
        -------
        ColumnSchema
            New ColumnSchema instance with the given columns and role.
        """
        tags = {}
        for col in columns:
            tag = ColumnTag.decode(col)  # role=role
            if tag is not None:
                tags[col] = tag
        return cls(tags)

    def merge(
        self,
        other: "ColumnSchema",
        *,
        on_conflict: Literal["raise", "keep_self", "keep_other"] = "raise",
    ) -> "ColumnSchema":
        """
        Merge this ColumnSchema with another, handling conflicts according to
        the specified strategy.

        Parameters
        ----------
        other : ColumnSchema
            The other ColumnSchema to merge with.
        on_conflict : Literal["raise", "keep_self", "keep_other"], optional
            Strategy to handle conflicts:
            - "raise": raise an error if there are conflicting columns.
            - "keep_self": keep columns from this schema in case of conflict.
            - "keep_other": keep columns from the other schema in case of
               conflict.
            By default "raise".

        Returns
        -------
        ColumnSchema
            A new ColumnSchema instance that is the result of merging this
            schema with the other.

        Raises
        ------
        KeyError
            If there are conflicting columns and on_conflict is set to "raise".
        """
        overlap = set(self._tags) & set(other._tags)
        if overlap and on_conflict == "raise":
            raise KeyError(f"Column tag conflict on merge: {sorted(overlap)}")
        if on_conflict == "keep_self":
            merged = {**other._tags, **self._tags}
        else:  # keep_other oder kein overlap
            merged = {**self._tags, **other._tags}
        return ColumnSchema(merged)

    @classmethod
    def from_legacy(
        cls,
        columns: Iterable[str],
        sample_names: list[str],
        parser: Callable[[str, list[str]], ColumnTag | None] = _legacy_to_tag,
    ) -> tuple["ColumnSchema", dict[str, str]]:
        """
        Convert legacy column names to a new ColumnSchema and provide a rename
        mapping.

        This method parses legacy column names using the provided parser,
        constructs a new ColumnSchema with the recognized columns, and returns
        a mapping from the original column names to the new canonical names.

        Returns
        -------
        tuple[ColumnSchema, dict[str, str]]
            A tuple containing the new ColumnSchema and a rename mapping from
            old column names to new canonical names.

        Raises
        ------
        ValueError
            If there are duplicate columns after renaming.
        """
        tags: dict[str, ColumnTag] = {}
        rename: dict[str, str] = {}
        for col in columns:
            tag = parser(col, sample_names)
            if tag is None:
                continue
            new_name = tag.encode()
            if new_name in tags:
                raise ValueError(
                    f"Duplicate column after rename: {new_name!r} (from {col!r})"  # noqa: E501
                )
            tags[new_name] = tag
            rename[col] = new_name
        return cls(tags), rename
